# Generated by Django 3.1.7 on 2021-06-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_createuserbio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Description', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dateAndTime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
