# Generated by Django 3.1.7 on 2021-06-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20210617_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
