# Generated by Django 3.1.7 on 2021-06-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='user',
            new_name='user_details',
        ),
    ]
