# Generated by Django 3.1.7 on 2021-06-17 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0011_auto_20210617_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_details',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
