# Generated by Django 3.1.7 on 2021-06-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0012_auto_20210617_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
