# Generated by Django 3.1.7 on 2021-06-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0021_auto_20210618_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='userDetails',
        ),
    ]
