# Generated by Django 3.1.7 on 2021-06-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0023_auto_20210618_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='userDetails',
            new_name='user',
        ),
    ]
