# Generated by Django 3.1.7 on 2021-06-19 14:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0024_auto_20210619_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
