# Generated by Django 3.1.7 on 2021-06-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0027_auto_20210619_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
