# Generated by Django 3.1.7 on 2021-06-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0029_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuserbio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
