# Generated by Django 3.1.7 on 2021-06-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0031_auto_20210619_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
