# Generated by Django 3.1.7 on 2021-06-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0036_auto_20210622_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='ProfileImage',
            field=models.ImageField(default='static/img/avatarLogo.jpg', null=True, upload_to=''),
        ),
    ]
