# Generated by Django 3.1.7 on 2021-06-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0037_auto_20210622_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='ProfileImage',
            field=models.ImageField(default='static/img/images/Screenshot_368.png', null=True, upload_to=''),
        ),
    ]
