# Generated by Django 3.1.7 on 2021-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0043_auto_20210702_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatarLogo.jpg', upload_to='media/img/'),
        ),
    ]
