# Generated by Django 3.1.7 on 2021-07-04 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0044_auto_20210702_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.CharField(blank=True, default='Hii i am using InstaBio', max_length=50)),
                ('Proffesion', models.CharField(blank=True, default='', max_length=100)),
                ('adress', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
