# Generated by Django 3.1.7 on 2021-07-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0047_auto_20210704_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otherUserDetails',
        ),
    ]
