# Generated by Django 3.1.7 on 2021-07-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0048_delete_otheruserdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Proffesion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='story',
            field=models.CharField(blank=True, default='Hii i am using InstaBio', max_length=50),
        ),
    ]
