# Generated by Django 3.1.7 on 2021-07-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0050_auto_20210717_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Proffesion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='For e.g Software Developer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='For e.g Badarpur,New Delhi,India'),
        ),
    ]
