# Generated by Django 3.1.7 on 2021-07-17 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0051_auto_20210717_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Proffesion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Your Proffesion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
