# Generated by Django 3.1.7 on 2021-07-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0058_auto_20210718_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuserbio',
            name='ShowOrHide',
        ),
        migrations.AlterField(
            model_name='createuserbio',
            name='image',
            field=models.ImageField(blank=True, default='avatarLogo.jpg', null=True, upload_to='media/img/'),
        ),
    ]
