# Generated by Django 3.1.7 on 2021-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0059_auto_20210718_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuserbio',
            name='image',
            field=models.ImageField(blank=True, default='avatarLogo.jpg', null=True, upload_to='img/media/share_icon/'),
        ),
    ]
