# Generated by Django 3.1.7 on 2021-07-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0060_auto_20210718_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuserbio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/media/share_icon/'),
        ),
    ]
