# Generated by Django 3.1.7 on 2021-07-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0061_auto_20210718_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuserbio',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/avatarLogo.jpg', null=True, upload_to='media/img/'),
        ),
    ]
