# Generated by Django 3.1.7 on 2021-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0062_auto_20210718_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuserbio',
            name='link_icon',
            field=models.CharField(blank=True, choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Fiverr', 'Fiverr')], default='', max_length=100),
        ),
    ]
