# Generated by Django 3.1.7 on 2021-07-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0063_createuserbio_link_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuserbio',
            name='imp_or_not',
            field=models.CharField(blank=True, choices=[('highlight', 'Highlight Link')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='createuserbio',
            name='link_icon',
            field=models.CharField(blank=True, choices=[('static_icon', 'Stactic Icon'), ('motion_icon', 'Motion Icon'), ('Fiverr', 'fiverr')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='createuserbio',
            name='title',
            field=models.CharField(default='username', max_length=32),
        ),
    ]
