# Generated by Django 3.1.7 on 2021-07-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0064_auto_20210726_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuserbio',
            name='imp_or_not',
        ),
    ]
