# Generated by Django 3.1.7 on 2021-08-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0065_remove_createuserbio_imp_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuserbio',
            name='link_icon',
            field=models.CharField(blank=True, choices=[('Motion_icon', 'Motion Icon'), ('Important_icon', 'Important')], default='', max_length=100),
        ),
    ]
