# Generated by Django 3.1.7 on 2021-08-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0066_auto_20210805_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuserbio',
            name='page_views',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
