# Generated by Django 3.1.7 on 2021-08-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0067_createuserbio_page_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuserbio',
            name='page_views',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
